import { Product } from './Product';

export const PRODUCTS: Product[] = [
  {
    "category": "chairs",
    "id": 1,
    "imgSrc": "assets/img/products/chairs/ch-1.png",
    "title": "Cтул ханна",
    "price": 9399,
    "currency": "₽",
    "count": 7,
  },
  {
    "category": "chairs",
    "id": 2,
    "imgSrc": "assets/img/products/chairs/ch-2.png",
    "title": "Cтул Эдинбург",
    "price": 9399,
    "currency": "₽",
    "count": 1
  },
  {
    "category": "chairs",
    "id": 3,
    "imgSrc": "assets/img/products/chairs/ch-3.png",
    "title": "Cтул Сольер",
    "price": 9399,
    "currency": "₽",
    "count": 4,
  },
  {
    "category": "chairs",
    "id": 4,
    "imgSrc": "assets/img/products/chairs/ch-4.png",
    "title": "Cтул Стелла",
    "price": 9399,
    "currency": "₽",
    "count": 2,
  },
  {
    "category": "chairs",
    "id": 5,
    "imgSrc": "assets/img/products/chairs/ch-5.png",
    "title": "Cтул Бланес",
    "price": 9399,
    "currency": "₽",
    "count": 1,
  },
  {
    "category": "chairs",
    "id": 6,
    "imgSrc": "assets/img/products/chairs/ch-6.png",
    "title": "Кресло Гоа",
    "price": 9399,
    "currency": "₽",
    "count": 3,
  },
  {
    "category": "chairs",
    "id": 8,
    "imgSrc": "assets/img/products/chairs/ch-8.png",
    "title": "Кресло Мильтон",
    "price": 9399,
    "currency": "₽",
    "count": 4,
  },
  {
    "category": "chairs",
    "id": 9,
    "imgSrc": "assets/img/products/chairs/ch-9.png",
    "title": "Кресло Рикардо",
    "price": 9399,
    "currency": "₽",
    "count": 6,
  },
  {
    "category": "chairs",
    "id": 10,
    "imgSrc": "assets/img/products/chairs/ch-10.png",
    "title": "Cтул Версаль",
    "price": 9399,
    "currency": "₽",
    "count": 9,
  },
  {
    "category": "chairs",
    "id": 11,
    "imgSrc": "assets/img/products/chairs/ch-11.png",
    "title": "Cтул Лина",
    "price": 9399,
    "currency": "₽",
    "count": 2,
  },
  {
    "category": "chairs",
    "id": 12,
    "imgSrc": "assets/img/products/chairs/ch-12.png",
    "title": "Кресло Софья",
    "price": 9399,
    "currency": "₽",
    "count": 22,
  },
  {
    "category": "chairs",
    "id": 13,
    "imgSrc": "assets/img/products/chairs/ch-13.png",
    "title": "Кресло Софья",
    "price": 9399,
    "currency": "₽",
    "count": 6,
  },
  {
    "category": "chairs",
    "id": 14,
    "imgSrc": "assets/img/products/chairs/ch-14.png",
    "title": "Кресло Софья",
    "price": 9399,
    "currency": "₽",
    "count": 1,
  },
  {
    "category": "chairs",
    "id": 15,
    "imgSrc": "assets/img/products/chairs/ch-15.png",
    "title": "Кресло Софья",
    "price": 9399,
    "currency": "₽",
    "count": 5,
  },
];
